package com.group18.capstone.controller;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.UUID;

public class NewEmailNotifier implements IObserver{
    private UUID UUIDrandom;
    private String emailAddress;
    private String firstName;
    UserBuilder newState;


    public NewEmailNotifier(UserBuilder newState){
        this.newState = newState;
        newState.addObserver(this);
    }


    @Override
    public void update(UUID randomuuid, String emailAddress, String firstName) {
        this.UUIDrandom = randomuuid;
        this.emailAddress = emailAddress;
        this.firstName = firstName;
        sendEmail();
    }


    // MOCK UP EMAIL SENT ON REGISTRATION
    public void sendEmail(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        System.out.println("Notifier: New email registered! "+emailAddress);
        System.out.println("***MOCK UP***");
        System.out.println("***This is what the user would see if they received an email***");
        System.out.println("----------------------------------------------");
        System.out.println("RestCo Account Verification");
        System.out.println("RestCo <no-reply@Restco.com>");
        System.out.println(dtf.format(now));
        System.out.println("To: "+emailAddress);
        System.out.println("        Hello "+firstName+",");
        System.out.println("We are pleased to welcome you to our family!");
        System.out.println("This email was sent when you sent a request to register on our web application");
        System.out.println("Please keep this email for your records.");
        System.out.println("To save on energy this email was generated by eco-friendly server with identifier: "+UUIDrandom);
        System.out.println("RestCo© 2021 copyright. All Rights Reserved.");
        System.out.println("");
        System.out.println("");
    }
}
